version: "3.8"
services:
#  api:
#    container_name: FastAPI_Ylab
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    networks:
#      - mynetwork
#    ports:
#      - "8000:8000"
#    depends_on:
#      db:
#        condition: service_healthy
  db:
    container_name: "postgres-db"
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DBUSER:-postgres}
      - POSTGRES_PASSWORD=${DBPASSWORD:-postgres}
      - POSTGRES_DB=${DBNAME:-postgres}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DBNAME} -U ${DBUSER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
networks:
  mynetwork:
    driver: bridge
