"""Change descriptions constraint

Revision ID: 643781f8f572
Revises: 80f5349b8b9b
Create Date: 2023-01-14 22:04:33.581213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "643781f8f572"
down_revision = "80f5349b8b9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("menu_description_key", "menu", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("menu_description_key", "menu", ["description"])
    # ### end Alembic commands ###
