"""Add cascade deleting

Revision ID: 9edc3529b872
Revises: 643781f8f572
Create Date: 2023-01-15 01:47:36.868502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9edc3529b872"
down_revision = "643781f8f572"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
